image: mhart/alpine-node:6

.test: &test
  script:
    - npm install && npm test

test-node-4:
  image: mhart/alpine-node:4
  <<: *test

test-node-5:
  image: mhart/alpine-node:5
  <<: *test

test-node-6:
  image: mhart/alpine-node:6
  <<: *test
